#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 19, 2019 04:06:57 PM +0800  platform: Windows NT
#    May 19, 2019 06:05:29 PM +0800  platform: Windows NT
#    May 19, 2019 09:00:47 PM +0800  platform: Windows NT
#    May 20, 2019 07:41:15 PM +0800  platform: Windows NT
#    May 20, 2019 09:48:10 PM +0800  platform: Windows NT
#    May 20, 2019 11:32:23 PM +0800  platform: Windows NT

import itchat
import sys
import os

sys.path.append(os.path.abspath(os.path.dirname(os.getcwd())))

import seq2seq.word.test_model_word as test_model_word
import seq2seq.word.data_word as data_word
import answers.Match as match
import soliloquize.wechat as wechat

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

@itchat.msg_register(itchat.content.TEXT,isMpChat=True)
def receive(msg):
    w.Dialog.config(state=tk.NORMAL)
    
    TSays=msg['Text']

    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,TSays+'\n')
    w.Dialog.tag_add('tulpa'+line,line,'end')
    w.Dialog.tag_config('tulpa'+line,justify="left")

    w.Dialog.config(state=tk.DISABLED)
    w.Host.config(state=tk.NORMAL)
    w.Tulpa.config(state=tk.DISABLED)


def onSoliloquize():
    print('unknown_support.onSoliloquize')
    w.Dialog.config(state=tk.NORMAL)

    HSays=w.HostSays.get()
    
    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,HSays+'\n')
    w.Dialog.tag_add('host'+line,line,'end')
    w.Dialog.tag_config('host'+line,justify="right")
    w.HostSays.delete(0,tk.END)

    wechat.start();
    wechat.send(HSays);

    w.Dialog.config(state=tk.DISABLED)
    w.Host.config(state=tk.NORMAL)
    w.Tulpa.config(state=tk.DISABLED)
    sys.stdout.flush()

def onClean():
    print('unknown_support.onClean')
    w.Dialog.config(state=tk.NORMAL)
    w.Dialog.delete('0.0',tk.END)
    w.Dialog.config(state=tk.DISABLED)
    w.Host.config(state=tk.NORMAL)
    w.Tulpa.config(state=tk.NORMAL)
    sys.stdout.flush()

def onAnswers():
    print('unknown_support.onAnswers')
    w.Dialog.config(state=tk.NORMAL)

    HSays=w.HostSays.get()
    
    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,HSays+'\n')
    w.Dialog.tag_add('host'+line,line,'end')
    w.Dialog.tag_config('host'+line,justify="right")
    w.HostSays.delete(0,tk.END)

    TSays=match.fromStr(HSays)

    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,TSays+'\n')
    w.Dialog.tag_add('tulpa'+line,line,'end')
    w.Dialog.tag_config('tulpa'+line,justify="left")

    w.Dialog.config(state=tk.DISABLED)
    w.Host.config(state=tk.NORMAL)
    w.Tulpa.config(state=tk.DISABLED)
    sys.stdout.flush()

def onDataGen():
    print('unknown_support.onDataGen')
    data_word.process_data()
    sys.stdout.flush()

def onSeq2Seq():
    print('unknown_support.onSeq2Seq')
    
    w.Dialog.config(state=tk.NORMAL)

    HSays=w.HostSays.get()
    
    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,HSays+'\n')
    w.Dialog.tag_add('host'+line,line,'end')
    w.Dialog.tag_config('host'+line,justify="right")
    w.HostSays.delete(0,tk.END)

    TSays=test_model_word.TulpaAvatar(HSays)

    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,TSays+'\n')
    w.Dialog.tag_add('tulpa'+line,line,'end')
    w.Dialog.tag_config('tulpa'+line,justify="left")

    w.Dialog.config(state=tk.DISABLED)
    w.Host.config(state=tk.NORMAL)
    w.Tulpa.config(state=tk.DISABLED)

    sys.stdout.flush()

def onExport():
    print('unknown_support.onExport')
    f = open("data\conv_zh.txt",'a',encoding='utf-8')
    f.writelines("\n"+w.Dialog.get('0.0',tk.END).rstrip('\n'))
    f.close()
    sys.stdout.flush()

def onBtnHostSays():
    print('unknown_support.onBtnHostSays')

    HSays=w.HostSays.get()
    
    w.Dialog.config(state=tk.NORMAL)
    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,HSays+'\n')
    w.Dialog.tag_add('host'+line,line,'end')
    w.Dialog.tag_config('host'+line,justify="right")
    w.HostSays.delete(0,tk.END)
    w.Host.config(state=tk.DISABLED)
    w.Tulpa.config(state=tk.NORMAL)
    w.Dialog.config(state=tk.DISABLED)
    sys.stdout.flush()

def onBtnTulpaSays():
    print('unknown_support.onBtnTulpaSays')

    TSays=w.TulpaSays.get()
    
    w.Dialog.config(state=tk.NORMAL)
    line=w.Dialog.index(tk.INSERT)
    w.Dialog.insert(tk.INSERT,TSays+'\n')
    w.Dialog.tag_add('tulpa'+line,line,'end')
    w.Dialog.tag_config('tulpa'+line,justify="left")
    w.TulpaSays.delete(0,tk.END)
    w.Tulpa.config(state=tk.DISABLED)
    w.Host.config(state=tk.NORMAL)
    w.Dialog.config(state=tk.DISABLED)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()




